apiVersion: v1
kind: Pod

metadata:
  name: gpu-pod

spec:
  containers:
    - name: gpu-container
      image: gitlab-registry.nrp-nautilus.io/jhurt/gpu-ci:2a86a247
      imagePullPolicy: IfNotPresent
      command: ["sleep", "infinity"]
      resources:
        limits:
          memory: 12Gi
          cpu: 2
          nvidia.com/gpu: 1
        requests:
          memory: 12Gi
          cpu: 2
          nvidia.com/gpu: 1
      volumeMounts:
        - mountPath: /dev/shm
          name: dshm
  volumes:
    - name: dshm
      emptyDir:
        medium: Memory
  affinity:
    nodeAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
        - weight: 1
          preference:
            matchExpressions:
              - key: nvidia.com/gpu.product
                operator: In
                values:
                  - NVIDIA-A100-80GB-PCIe-MIG-1g.10gb
              - key: topology.kubernetes.io/region
                operator: In
                values:
                  - us-central
